Clean up constants based on file/dir
dwellir-public/polkadot-operator pull request #65
Opened 2024-05-10 08:12 UTC by ZeeshanM96

### Description:
Constants in the constants.py should be named after what they represent e.g. `_DIR` for directories and `_FILE` for files.

### Screenshots:
![jujustatus](https://github.com/dwellir-public/polkadot-operator/assets/116648836/70664d63-9201-4522-bd93-6d072b5b642b)

![logs](https://github.com/dwellir-public/polkadot-operator/assets/116648836/3f876023-c509-4675-9007-9e64d0c472bf)

2024-05-10 08:21 UTC, awnns commented
I believe the USER constant was supposed to remain. There is a separate constant for the user's home directory already.

2024-05-10 08:25 UTC, awnns commented
Also probably, we should use names like "HOME_DIR" instead of "HOME_PATH_DIR" in the interest of avoiding https://en.wikipedia.org/wiki/Tautology_(language).

2024-05-10 08:26 UTC, ZeeshanM96 commented
@awnns I tried looking up for `USER_DIR`, and couldn't find any. All of the `USER_DIR` are coming from the `constant.py` file. Please correct me if I am wrong.

![Screenshot from 2024-05-10 10-22-37](https://github.com/dwellir-public/polkadot-operator/assets/116648836/ebbb08fb-0fd6-410d-bbc2-56d367d5afc6)

2024-05-10 08:27 UTC, awnns commented
> @awnns I tried looking up for `USER_DIR`, and couldn't find any. All of the `USER_DIR` are coming from the `constant.py` file. Please correct me if I am wrong.
> 
> ![Screenshot from 2024-05-10 10-22-37](https://private-user-images.githubusercontent.com/116648836/329513362-ebbb08fb-0fd6-410d-bbc2-56d367d5afc6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzMjk5MjYsIm5iZiI6MTcxNTMyOTYyNiwicGF0aCI6Ii8xMTY2NDg4MzYvMzI5NTEzMzYyLWViYmIwOGZiLTBmZDYtNDEwZC1iYmMyLTU2ZDM2N2Q1YWZjNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMFQwODI3MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NWVhNTI0MGM3YWRiZjYwOGFjODZkMmVlNjE2OTY0N2RlODM0NDMwODgyN2VmMTgzY2M0YTk5MjEwNjYyNDE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.a46uj5SCJJ1dbqpMRIxmYNGohPqFW_O2PoNRi9XZCt4)

![image](https://github.com/dwellir-public/polkadot-operator/assets/108928853/668a28ef-3419-43b3-a4bf-066028bf4d59)

2024-05-10 09:19 UTC, ZeeshanM96 commented
@jonathanudd @awnns i have made the naming convention better. Please have a look and let me know if you have any remarks

2024-05-10 09:59 UTC, ZeeshanM96 commented on src/constants.py
> +USER_DIR = 'polkadot'
Yes, I have updated the changes and ran the charm normally and also with service arguments to see the service getting restarted and log that's `config-changed`. I have attached screenshots in the descriptions as well.
e.g: `unit-polkadot-0: 11:45:12 INFO juju.worker.uniter.the operation ran "config-changed" hook (via hook dispatching script: dispatch)`

2024-05-10 11:19 UTC, jakobilobi approved these changes

2024-05-13 13:26 UTC, awnns requested changes
You have not ensured that all uses of the constants have had their names changed to the name in the new constants file. The version you proposed would break the charm and cause numerous functions to throw exceptions.

2024-05-14 07:01 UTC, merged